// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgtsasanlonnovvdwril.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtndHNhc2FubG9ubm92dmR3cmlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMzg5MjUsImV4cCI6MjA2MjkxNDkyNX0.AfHDfX1tQUKoNTzDDEVMC3h87MDO6MqIiNnG6g-SZfE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);